### ISSUE TITLE
is the "Open an Issue" href correct?

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-repo-template#1]
Hi Code.gov peeps,

Awesome template. I have a question about the "Open an Issue" link in the [Questions? section of your README.md](https://github.com/GSA/code-gov-repo-template/blob/master/README.md#questions). Is it intentional to route all questions to your frontend repo?

Thanks for all the hard work!!!! 🎉 :heart:

**Comment by saracope** [comment]
No, it shouldn't be. I was trying to look through the GH docs and see if there's a way to do a relative link to Issues, but haven't found if that's possible. I'd like this href to not have to be updated each time we clone since it's meant to be a template.  Do you know if that's possible?

**Comment by froi** [comment]
Got it! I'm unsure if that's possible but I will verify 😄

**Comment by CourtneyBrousseau** [comment]
The links that relate to issues on the CONTRIBUTING.md have the same problem in theory (and are also currently broken in practice)

**Comment by saracope** [comment]
Yeah, it's the same issue. They all need updating when this is figured out. Just leaving them for now.

**Comment by CourtneyBrousseau** [comment]
I removed the links to the issues page to avoid this issue. If there's anyway to add the links back we can revisit this later
